### ISSUE TITLE
Missing Management API Token

### ISSUE THREAD

**Issue by mikemowgli** [innovationnorway/terraform-provider-databricks#45]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.16

### Affected Resource(s)
databricks_cluster

### Terraform Configuration Files
```hcl
provider "azurerm" {
  features {}
}

provider "databricks" {
  host  = format("https://%s.azuredatabricks.net", azurerm_databricks_workspace.data-test.location)
  azure {
    workspace_id = azurerm_databricks_workspace.data-test.id
  }
}

resource "databricks_cluster" "data-test" {
  cluster_name  = "data-test"
  spark_version = "6.3.x-scala2.11"
  node_type_id  = "Standard_F4s"
  autoscale {
    min_workers = 1
    max_workers = 2
  }
  spark_conf = {
    "spark.databricks.delta.preview.enabled" = true
  }
  autotermination_minutes = 120
}
```

### Debug Output
```
databricks_cluster.data-test: Creating...

Error: unable to create cluster: clusters.BaseClient#Create: Failure responding to request: StatusCode=400 -- Original Error: error response cannot be parsed: "<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 400 Management API token must be provided for service principal admin user login.</title>\n</head>\n<body><h2>HTTP ERROR 400</h2>\n<p>Problem accessing /api/2.0/clusters/create. Reason:\n<pre>    Management API token must be provided for service principal admin user login.</pre></p>\n</body>\n</html>\n" error: invalid character '<' looking for beginning of value

  on databricks.tf line 2, in resource "databricks_cluster" "data-test":
   2: resource "databricks_cluster" "data-test" {
```

### Expected Behavior
Databricks cluster created.

### Actual Behavior
Above error message appeared

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
* Running in Azure.
* the environment variables  ARM_TENANT_ID,  DATABRICKS_AZURE_CLIENT_ID, DATABRICKS_AZURE_CLIENT_SECRET are set to a SP that has owner permissions on the subscription.
* I also tried setting the `token` option in the `databricks` provider, with a Personal Access Token I manually created in the UI (which defeats the purpose of automation) with same result.

### References
* token created with: https://docs.databricks.com/dev-tools/api/latest/authentication.html#authentication
* this provider's doc: https://github.com/innovationnorway/terraform-provider-databricks/blob/master/website/docs/d/databricks_cluster.html.markdown

**Comment by joakimhellum** [comment]
@mikemowgli Sorry about that, we are working on improving auth experience and error messages.

For Azure AD authentication using Service Principal, could you please try the following:

1. First set the following environment variables, then run `terraform apply`:
```
export DATABRICKS_AZURE_CLIENT_ID=<app-id>
export DATABRICKS_AZURE_CLIENT_SECRET=<client-secret>
export DATABRICKS_AZURE_TENANT_ID=<tenant-id>
terraform init
terraform apply
```

For Azure AD authentication using Azure CLI (for local development), could you please try the following:
```
az login
az account set -s <your-subscription>
terraform init
terraform apply
```

Reference to https://github.com/innovationnorway/terraform-provider-databricks/blob/master/website/docs/index.html.markdown#argument-reference

**Comment by mikemowgli** [comment]
@joakimhellum , thank you for the quick answer.
Ok I was missing the service_principal block indeed. However an empty block wasn't enough and I had to define at least the 'tenant_id' option.

**Comment by joakimhellum** [comment]
@mikemowgli Thanks!

It should be possible to specify an empty `service_principal` block, and then set the `DATABRICKS_AZURE_CLIENT_ID`, `DATABRICKS_AZURE_CLIENT_SECRET`, `DATABRICKS_AZURE_TENANT_ID` environment variables. 

We realize this does not provide the best user experience currently and very least should be documented. Will keep this issue open for a few days while we work on improving the authentication experience and error messages, so we can notify you once it's fixed :)

Thanks for your patience,
